vega/vega-datasets

data/cars.json

Replaces dates of the format `YYYY` with dates of the format `YYYY-01-01` since the former is not supported.

Fix cars.json date issue

---

data/iowa-electricity.csv
sources.md

During a discussion in [Altair issue #817](https://github.com/altair-viz/altair/pull/817), our group came to the conclusion that the existing dataset for illustrating stacked area charts, [unemployment across industries](https://vega.github.io/vega-lite/examples/stacked_area_normalize.html), is less than ideal.
Its large number of categories yield a noisy chart. And the mix of values don't change enough over time to make for an interesting normalized chart. See for yourself:
To try to provide a stronger example to users, we developed a checklist for selecting a better dataset. We settled on:
- Require no data transformations 
- A time series 
- A small number of categories
- Values are percentages of a whole
- Tell an obvious, interesting visual "story."
After some back and forth, we …

Add stacked area example

---

.autorc.json
.github/workflows/merge-dependabot.yml
.github/workflows/publish.yml
.github/workflows/test.yml
README.md
package.json
yarn.lock

- Less time spent on managing package infra . See parent task https://github.com/orgs/vega/projects/8#card-69515101
- Replicate the setup in https://github.com/vega/vega-embed/pull/749, + updates documentation
- CI should pass
-  [x] make `next` the base branch of this PR instead of `master`
-  [ ] make `next` the base branch for the whole repo 
-  [x] Create a branch called `stable` from the latest tag  `v2.1.0`  https://github.com/vega/vega-datasets/tree/stable
-  [x] Make a tagged release of the latest tag (exists, https://github.com/vega/vega-datasets/releases/tag/v2.1.0 )
-  [x] Create tags called `skip-release` and `released` in this repo (the first is used to tell auto not to release anything if this PR is released, the second is used to tag PRs that have been released).
<details> …

chore: set up auto for versioning/release management 

---

.github/workflows/publish.yml
.github/workflows/test.yml
package.json
src/data.ts
yarn.lock

<details>
<summary>📦 Published PR as canary version: <code>2.4.1--canary.384.8ab3149.0</code></summary>
<br />
:sparkles: Test out this PR locally via:
```bash
npm install vega-datasets@2.4.1--canary.384.8ab3149.0
yarn add vega-datasets@2.4.1--canary.384.8ab3149.0
```
</details>

chore: simplify token setup, update deps

---

rollup.config.js

fixes #391
<details>
<summary>📦 Published PR as canary version: <code>2.5.2--canary.393.6152f95.0</code></summary>
<br />
:sparkles: Test out this PR locally via:
```bash
npm install vega-datasets@2.5.2--canary.393.6152f95.0
yarn add vega-datasets@2.5.2--canary.393.6152f95.0
```
</details>

fix: switch back to UMD bundles

---

package.json
rollup.config.js
yarn.lock

<details>
<summary>📦 Published PR as canary version: <code>2.5.3--canary.395.5228498.0</code></summary>
<br />
:sparkles: Test out this PR locally via:
```bash
npm install vega-datasets@2.5.3--canary.395.5228498.0
yarn add vega-datasets@2.5.3--canary.395.5228498.0
```
</details>

fix: add resolve to include d3 dependency

---

README.md

This pull request addresses part of #577 by updating the README file with a data usage note. 
Still to be done (also tracked in #577): 
- refresh gapmider.json from gapminder source
- update SOURCES.md with sourcing information for the dataset

docs: updates README.md with data usage note

---

SOURCES.md
data/monarchs.json

Resolves #595
Before approving, please review how the dataset corrections will alter the example visualization `Wheat and Wages` appearing in the [Vega](https://vega.github.io/vega/examples/wheat-and-wages/), [Vega-Lite](https://vega.github.io/vega-lite/examples/wheat_wages.html) and [Altair](https://altair-viz.github.io/gallery/wheat_wages.html) example galleries. 
[Original](https://vega.github.io/vega-lite/examples/wheat_wages.html) from vega-lite gallery
[Modified](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAdxoATemgCcABh1L4NMljQAWPUrVJMKVKAYAnQWhBWbBZfGtSZ8gL5KmA5IshAAZmwOCGgA2qBQSIJQDILWcC4A1G4MCJQAnnBIDgAEGcViiiBIEC4FRQD6cLJqIH4AukpNUGxqNLJkaKB5gyCYeTjp6ACODCGYdNY0pJVIAB40NXYgAF59anCraACMfgEgh1 …

feat:  correct monarchs.json and add source information

---

SOURCES.md

SOURCES.md previously showed only a reference to `flare.json`, not to the related file `flare-dependencies.json` that [exists](https://github.com/vega/vega-datasets/blob/main/data/flare-dependencies.json) in the data folder

docs: adds missing reference to flare-dependencies.json to SOURCES.md

---

scripts/flights.py

- Modified `scripts/flights.py` to handle parquet output with customizable compression 
- To address [#627](https://github.com/vega/vega-datasets/issues/627), generated `data/flights-3m` dataset using:
```bash
python scripts/flights.py /path/to/DOT/zip/files \
-f parquet \
--parquet-compression zstd \
--start-date 2001-01-01 \
--end-date 2001-06-30 \
-c date,delay,distance,origin,destination \
-o data/flights-3m \
-n 3000000
```
Note: Replace /path/to/DOT/zip/files with the local directory containing the Bureau of Transportation Statistics (BTS) monthly ZIP files from [their website](https://www.transtats.bts.gov/DL_SelectFields.asp?gnoyr_VQ=FGJ&QO_fu146_anzr=b0-gvzr). Download prezipped files, one per month.

fix: replace data/flights-3m.csv with data/flights-3m.parquet

---

datapackage.json
scripts/flights.py

Closes #641 
- https://github.com/vega/altair/pull/3631#issuecomment-2480816377
If I've understood the *existing* script correctly; then this should produce a datetime/timestamp column for `"date"`.
Or more correctly, it won't convert to a format string for `.parquet` - as it supports data types.
@dsmedia I haven't run the script, as I'm unsure on:
- What environment is needed for the script?
- How exactly is the [linked data](https://www.transtats.bts.gov/DL_SelectFields.asp?gnoyr_VQ=FGJ&QO_fu146_anzr=b0-gvzr) selected?
- The doc says 1 per month
- `flights-3m.parquet` has 6 months
- `flights-?k.json` have 3 months?
- What were the most recent CLI args used?
In (https://github.com/vega/vega-datasets/pull/642/commits/a908adb8477c9b7cdebc42a77eda3c381b2c8292) I opted for making the change …

feat: Use a datetime column in `flights-3m.parquet`

---

.gitignore

Not as exhaustive as https://github.com/vega/altair/blob/main/.gitignore, but has been enough so far on my previous PRs

ci: adds python-specific `.gitignore` patterns

---

.github/workflows/test.yml
pyproject.toml
taplo.toml
uv.lock

Will close #646
This PR adds formatting of `.toml` via `taplo` and formatting & linting of `python` with `ruff`.
The `ruff` config is based on what we use for `altair` in (https://github.com/vega/altair/blob/main/pyproject.toml)
I've **disabled** `ruff` for essentially anything that I haven't written.
If there is a desire to clean up old code, we can work on reducing the scripts listed in follow-up PRs:
https://github.com/vega/vega-datasets/blob/c48731b737c0ab95ec9420f096aad65429eb6d94/pyproject.toml#L18-L30
> [!NOTE]
> The `build_datapackage.py` [exclusion](https://github.com/vega/vega-datasets/pull/647/commits/c48731b737c0ab95ec9420f096aad65429eb6d94) will be dropped after this is merged.
> I fixed these already in (https://github.com/vega/vega-datasets/pull/643/commits/fbd1be573bb3257d5 …

ci: adds `taplo.toml`, `pyproject.toml`

---

README.md

I used https://github.com/vega/vega-datasets/tree/next in (https://github.com/vega/vega-datasets/pull/643/commits/d550d8a862165854240b6b7777feae0f9da65937) as that was the branch listed previously, but that branch is outdated.
Updates to https://github.com/vega/vega-datasets/tree/main

docs: fix invalid `README.md` links

---

.gitattributes
datapackage.json
datapackage.md

Resolves:
- https://github.com/vega/vega-datasets/pull/648#issuecomment-2557981044
- https://github.com/vega/vega-datasets/pull/648#issuecomment-2558086569
It turns out [os.stat_result.st_size](https://docs.python.org/3/library/os.html#os.stat_result.st_size) wasn't the issue.
Essentially, traces back to [configuring-git-to-handle-line-endings](https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings#global-settings-for-line-endings)
I forgot that I set  `--global core.autocrlf true`, which I'd overriden in `altair` 
- [vega/altair@`fa5fe6f` (#3523)](https://github.com/vega/altair/pull/3523/commits/fa5fe6f93bf6994d582477e6078f5207d8679db6)
I've now forced that to `false` everywhere I could locally, and added a `.gitattributes` in case this …

fix: fix `CRLF`-inflated `Resource.bytes` size

---

datapackage.json
datapackage.md
scripts/flights.py

Fixes #655
The file size of `flights-200k.arrow` has a ~~**7.2x**~~ **2.4x increase.**
However, this is still ~~roughly **half**~~ **0.16x** the size of `flights-200k.json`.
Also, adds support for overriding any `write_options` on a per-`Spec` basis.
This may be helpful if we later run into issues with https://github.com/vega/vega/issues/3961

fix: Change default `.arrow` compression to `"uncompressed"`

---

datapackage.json
datapackage.md
scripts/build_datapackage.py

- https://datapackage.org/standard/data-resource/#hash
This PR adds a hash for each dataset, piggybacking directly from the [GitHub trees API](https://docs.github.com/en/rest/git/trees?apiVersion=2022-11-28).
<details><summary>More info</summary>
<p>
https://github.com/vega/vega-datasets/blob/062ee8a37b1eeef4b3368ac48af024706f6d96ea/scripts/build_datapackage.py#L520-L547
</p>
</details> 
Mostly just upstreaming existing code from https://github.com/vega/altair/blob/fdffed0a15be3967c6b9513787fd40feb59c9cdc/tools/datasets/github.py#L145-L159 with some tweaks.
I think this is a broadly useful inclusion to `datapackage.json`, since we have **74** datasets that have very few revisions.
I've been using this in https://github.com/vega/altair/pull/3631 for [caching datasets across …

feat: adds `Resource.hash` in `datapackage.json`

---

README.md

Links will help users find practical implementations in the official example galleries.
@dangotbanned once altair begins to use this repo, let's add a link to this file as well.

docs: add URLs to vega/vega-lite example galleries in README.md

---

.github/workflows/test.yml
taplo.toml

Addresses issue #705.
This PR updates the CI workflow in `.github/workflows/test.yml` to use `uv run` instead of `uvx` for executing our linting and formatting tools (`ruff` and `taplo`).
**Why this change?**
* **Ensures Locked Versions:** This change guarantees that our CI pipeline uses the exact versions of `ruff` and `taplo` that are pinned in our `uv.lock` file. Previously, `uvx` might not have strictly adhered to these locked versions for the tools themselves.
* **Reproducibility & Consistency:** By using `uv run`, we align the CI environment more closely with local development setups when using `uv`. This command activates the project's managed environment, ensuring that the same tool versions are used everywhere, which is crucial for reproducible builds.
* **Best Practice:** `uv …

ci: Use uv run for dev tools to ensure locked versions

---

datapackage.json
datapackage.md
scripts/build_datapackage.py
scripts/species.py

This PR updates dataset names in `datapackage.json` to be UAX-31 compliant, making them valid Python identifiers. The changes only affect the `name` fields while keeping the `path` fields unchanged.
I'm not sure if this is sufficient to close #695, but otherwise it can serve as a starting point for a discussion towards closing the related issue.
- Converted hyphens to underscores in names
- Removed file extensions (`.json`, `.csv`, `.png`) from all dataset names
- Added `icon_` prefix to image files
- Ensured all names are valid Python identifiers
```diff
- "name": "7zip.png"
+ "name": "icon_7zip"
- "name": "annual-precip.json"
+ "name": "annual_precip"
```
Only oddities are related to extension `arrow` and `parquet`:
```diff
- "name": "flights_200k.arrow"
+ "name": "flights_200k_arrow"
- …
```

feat: Adopt UAX-31 compliant dataset names
